### ISSUE TITLE
train

### ISSUE THREAD

**Issue by SureT-T** [zhengchen1999/HI-Diff#21]
两张24g3090可以训练起来吗？

**Comment by zhengchen1999** [comment]
微调可以，完整训练不行

**Comment by gdsdfn75** [comment]
> 微调可以，完整训练不行

支队这两个gpu，如果我在s1预训练模型的基础上训练微调后的模型，Progressive training中的batch_sizes和gt_sizes怎样设定才算合适？

**Comment by SureT-T** [comment]
> 微调可以，完整训练不行

针对这两个gpu，如果我在s1预训练模型的基础上训练微调后的模型，Progressive training中的batch_sizes和gt_sizes怎样设定才算合适？
