### ISSUE TITLE
train

### ISSUE THREAD

**Issue by zhenyuan1234** [zhengchen1999/HI-Diff#7]
您好，请问如果训练过程中图像的patch size只采用一个尺寸，比如128，对性能会有什么影响

**Comment by zhengchen1999** [comment]
性能会下降。patch size的尺寸对于模型性能影响较大。
不过可以使用分块进行测试，会有效提升性能。

**Comment by zhenyuan1234** [comment]
感谢您的解答！请问这种渐进式的图像尺寸能提升性能的原因是什么，只用128或256训练性能为什么会下降。

**Comment by zhengchen1999** [comment]
渐进式的patch size，是[Restormer](https://github.com/swz30/Restormer)提出的。我个人认为，主要影响还是patch size的大小。256x256训练下的性能优于128x128。扩大patch size，性能进一步上升。渐进式的方式是为了提升训练速度，降低训练开销。因为训练前期使用小patch size，训练会更加高效。

**Comment by zhenyuan1234** [comment]
再次感谢您的回复!
