### ISSUE TITLE
Questions about Different Papers

### ISSUE THREAD

**Issue by dsjiaod** [zhengchen1999/HI-Diff#8]
[1] Diffir: Efficient diffusion model for image restoration. ICCV, 2023.
![image](https://github.com/zhengchen1999/HI-Diff/assets/152845676/abc5719c-f92d-49ee-82e8-67bdf006921b)
[2] Hierarchical Integration Diffusion Model for Realistic Image Deblurring. NeurIPS, 2023.
![image](https://github.com/zhengchen1999/HI-Diff/assets/152845676/6701255a-7e7a-48be-a365-700f08a3cd7c)
[3] Reti-Diff: Illumination Degradation Image Restoration with Retinex-based Latent Diffusion Model. arXiv preprint arXiv:2311.11638, 2023.
![image](https://github.com/zhengchen1999/HI-Diff/assets/152845676/2d1849d0-82a3-4d1c-bef8-6995787dcc6b)

**[1,2,3] almost adopt the same network structure and training strategy, and the novelty is consistent.**

**Comment by zhengchen1999** [comment]
Regarding the differences between HI-Diff and DiffBIR: 

We indicate in our paper that we reference the paradigm of DiffBIR, which combines Diffusion and Transformer. The distinction between HI-Diff and DiffIR lies in the **hierarchical integration**: **multi-scale prior** and **cross-attention interaction**, which is more apt for non-uniform realistic deblurring.

The prior is different. HI-Diff applies the multi-scale prior, while DiffIR uses the single-scale prior. The multi-scale prior adapts to different scale features in the encoder-decoder Transformer architecture for better integration.

The interaction is different. HI-Diff adopts cross-attention, while DiffIR uses prior as dynamic modulation parameters. Features pay different attention to the prior with cross-attention, which is more suitable for non-uniform deblurring.

Our method outperforms DiffIR with comparable parameters and FLOPs. This indicates that our approach, utilizing hierarchical integration, is more effective for realistic non-uniform deblurring.

<!DOCTYPE html>
Method | Params (M) | FLOPs (G) | PSNR (dB) | SSIM
-- | -- | -- | -- | --
DiffIR | 26.94 | 120.99 | 33.20 | 0.963
HI-Diff (ours) | 28.49 | 142.62 | 33.33 | 0.964
HI-Diff-2 (ours) | 23.99 | 125.47 | 33.28 | 0.964



PS: For [3], I am not very familiar with it, but applying this paradigm to other task is also a form of exploration.

**Comment by Riras-Misaka** [comment]
Congratulations for your wonderful story telling! Don't trouble the author, it is suggested to ask Yulun Zhang how many more tasks need to be done with this approach, and how many more papers need to be published.

**Comment by wangxinzhe0617** [comment]
e............................
