### ISSUE TITLE
What the license for this code

### ISSUE THREAD

**Issue by larsonwu0220** [zhengchen1999/HI-Diff#9]
Thank you for your and congratulations on being selected for the spotlight of NeurIPS 2023.
I would like to ask what the license is for this code?

Thanks a lot

**Comment by zhengchen1999** [comment]
We have released the license ([Apache-2.0 license](https://github.com/zhengchen1999/HI-Diff/blob/main/LICENSE)).

**Comment by larsonwu0220** [comment]
Thanks for your reply
